# Generated by Django 3.0.4 on 2020-03-18 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('abstractforecast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weather_forecast.AbstractForecast')),
                ('high_temperature_time', models.CharField(max_length=50)),
                ('high_temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('low_temperature_time', models.CharField(max_length=50)),
                ('low_temperature', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=('weather_forecast.abstractforecast',),
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('abstractforecast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weather_forecast.AbstractForecast')),
                ('time', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=('weather_forecast.abstractforecast',),
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_search', models.CharField(max_length=50)),
                ('entered_address', models.CharField(max_length=150)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abstractforecast',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_forecast.Search'),
        ),
    ]
